.github/workflows/post-merge-deploy-to-build.yml
.github/workflows/post-merge-deploy-to-dev.yml
infrastructure/template.yaml

Tried and tested changes necessary for the stack to be deployable via the pipelines
- Sam version change was necessary as 1.74.0 didn't accept `???` as a wildcard for permissions
- Code signing, permissions boundaries and function url changes were all necessary to allow the stack to deploy
- [OJ-1840](https://govukverify.atlassian.net/browse/OJ-1840)
[OJ-1840]: https://govukverify.atlassian.net/browse/OJ-1840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1840 allow pipelines to deploy hmrc kbv stack

---

.secrets.baseline
infrastructure/public-api.yaml

Add Issue Credential endpoint to the public-api.yaml
This endpoint calls a Step function that handles creating, generating claimset and signing it.
Needed as part the OAuth flow of the Credential Cri 
- [OJ-1841](https://govukverify.atlassian.net/browse/OJ-1841)
[OJ-1841]: https://govukverify.atlassian.net/browse/OJ-1841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1841: Added Issue Credential Endpoint

---

infrastructure/template.yaml
lambdas/submit-answer/src/create-auth-code-handler.ts
lambdas/submit-answer/tests/create-auth-code-handler.test.ts
step-functions/post-answer.asl.json

Added authorizationCode generation to the post answers state machine.
For now, this happens after we POST all the answers to HMRC
authorizationCodes are needed as part of the OAuth flow.
- [OJ-1904](https://govukverify.atlassian.net/browse/OJ-1904)
[OJ-1904]: https://govukverify.atlassian.net/browse/OJ-1904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1904: Added authorizationCode generation to the post answers state machine

---

lambdas/execute-state-machine/src/execute-state-machine-handler.ts

`execute-state-machine-handler.ts`
The Lambda does not throw an exception even though this is being caught in the get-ivq-questions state machine. To ensure that this error path is executed, the lambda now throws an error on exception.

OJ-1914: Added error logging and error throw

---

infrastructure/template.yaml
lambdas/evidence-check-details/.eslintignore
lambdas/evidence-check-details/.eslintrc.js
lambdas/evidence-check-details/jest.config.ts
lambdas/evidence-check-details/package-lock.json
lambdas/evidence-check-details/package.json
lambdas/evidence-check-details/src/check-details-handler.ts
lambdas/evidence-check-details/src/check-details.ts
lambdas/evidence-check-details/src/question-info-event.ts
lambdas/evidence-check-details/tests/check-details-handler.test.ts
lambdas/evidence-check-details/tsconfig.json
step-functions/issue-credential.asl.json

Replace evidence-check maps with lambda implementations
Not included in this PR is the loop for Create Credential Subject this would come as a separate PR
Remove map states for evidence-checking replaced with lambda implementations
Map states don't work with step-function local
- [OJ-1928](https://govukverify.atlassian.net/browse/OJ-1928)
[OJ-1928]: https://govukverify.atlassian.net/browse/OJ-1928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1928: replace evidence-check maps state with lambdas in hmrc kbv - part 1

---

infrastructure/private-api.yaml
lambdas/fetch-questions/src/fetch-questions-handler.ts
lambdas/fetch-questions/tests/fetch-questions-handler.test.ts
step-functions/get-ivq-questions.asl.json

This is a first pass at error handling for the get-ivq-questions.
The Lambda now catches exceptions, logs and re-throws. The Lambda will fail when there are no questions received from HMRC. 
The state machine has been changes to use pass states to represent 400s, fail states to represent 500s and success states for 200s. 
The OpenAPI file has been changes to return the correct status code depending on the returned error. 
We currently have no error handling in place so all requests gave a HTTP 200. 
- [OJ-1975](https://govukverify.atlassian.net/browse/OJ-1975)

OJ-1957: Add error handling to get-ivq-questions State Machine

---

lambdas/credential-subject/src/credential-subject-handler.ts

Move builder creation out handler
Best practice is to keep object initialization out of the handler

BAU: move object creation out of handler

---

lambdas/submit-answer/src/submit-answer-handler.ts
step-functions/post-answer.asl.json
step-functions/post-ivq-answers.asl.json

Added error handling to the `post-ivq-answers` state machine.
try-catch-throw to `SubmitAnswerHandler` so we can handle HMRC errors 
Updated `post-answers` state machine so that if `post-ivq-answers` fails, it is handled
- [OJ-1956](https://govukverify.atlassian.net/browse/OJ-1956)
[OJ-1956]: https://govukverify.atlassian.net/browse/OJ-1956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1956: Add error handling to `post-ivq-answers`

---

lambdas/submit-answer/src/submit-answer-handler.ts
lambdas/submit-answer/tests/submit-answer-handler.test.ts

`submit-answer-handler.ts` - In error scenarios, HMRC sometimes give text as a response instead of JSON so additional error handling has been added
`submit-answer-handler.test.ts` - Added unit test definition
Test coverage
- [OJ-1959](https://govukverify.atlassian.net/browse/OJ-1959)
[OJ-1959]: https://govukverify.atlassian.net/browse/OJ-1959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1959: `submit-answer-handler` unit tests

---

infrastructure/template.yaml

`template.yaml`
The private API gateway ID needs to be exported because this is required for the HMRC KBV frontend to know of the private API.

BAU: Added export for private APIGW

---

.github/workflows/check-pr.yml
.github/workflows/clean-up-deployments.yml
.github/workflows/delete-deployment.yml
.github/workflows/deploy-branch.yml
.github/workflows/run-unit-tests.yml
.github/workflows/scan-repo.yml
integration-tests/package.json

Use the SAM build cache instead of the artifact to improve performance.
Only archive SonarCloud test coverage report file

BAU: Use the latest shared GitHub Actions

---

.github/refresh-hmrc-token.sh
.github/workflows/run-aws-tests.yml
deploy.sh
integration-tests/tests/aws/jest.config.ts
integration-tests/tests/mocked/jest.config.ts

- The `whoami` alias might not be set up by default by the CLI so use the full command instead
- Fix jest config error
Fix the error `Can't find a root directory while resolving a config file path` when running an individual test rather than the whole suite.
**Automatically refresh the HMRC OAuth token for integration tests**
Run a script before each test that will check the token expiry and refresh it if there's less than 20 minutes to expiry at the time the tests run.
Job runs using the script:
- [Token is expired](https://github.com/govuk-one-login/ipv-cri-kbv-hmrc-api/actions/runs/7227082886/job/19694046431)
```
Run .github/refresh-hmrc-token.sh
Refreshing token...
Waiting for state machine execution...
Token has been refreshed
```
- [Token is …

BAU: Minor fixes to jest config and deployment script

---

.github/refresh-hmrc-token.sh
README.md
deploy.sh
infrastructure/template.yaml
integration-tests/tests/aws/get-ivq-questions/get-ivq-questions-happy.test.ts
integration-tests/tests/aws/get-question/get-question-happy.test.ts
integration-tests/tests/aws/post-answers/post-answers-happy.test.ts
integration-tests/tests/aws/post-ivq-answers/post-ivq-answers-happy.test.ts
lambdas/fetch-questions/package.json
lambdas/fetch-questions/src/fetch-questions-handler.ts
lambdas/fetch-questions/src/services/questions-retrieval-service.ts
lambdas/fetch-questions/src/types/questions-result-types.ts
lambdas/fetch-questions/tests/fetch-questions-handler.test.ts
lambdas/fetch-questions/tests/services/questions-retrieval-service.test.ts
lambdas/fetch-questions/tsconfig.json
lib/src/MetricTypes/handler-metric-types.ts
lib/src/MetricTypes/http-service-metrics.ts
lib/src/MetricTypes/metric-classifications.ts
lib/src/Service/metrics-probe.ts
package-lock.json
step-functions/get-ivq-questions.asl.json

- Deploy.sh
- add fall back default common_stack_name to deploy.sh
- Template
- add env var AuditEventNamePrefix for audit event prefix
- add env var CriIdentifier for power tools logging and metrics
- add env vars for stackname
- and env POWERTOOLS_METRICS_NAMESPACE/POWERTOOLS_SERVICE_NAME for metrics (namespace = cri, service - per lambda)
- increase fetchquestions timeout to 15 seconds to account for stub warmup
- add name to fetchquestions to keep lambda naming consistent between environments and simplify dashboard reuse.
- added lib for shared objects
- metrics probe
- - metrics types added
- - service metrics labled by service type
- FetchQuestionsHandler / fetch questions lambda
- changed unit test output to verbose
- handler returns retrieved question count
- - metrics added for …

LIME-1080 - Update endpoint that will get questions from HMRC

---

infrastructure/private-api.yaml

Correct case of fetch questions endpoint to `/fetchquestions`
Case was incorrectly set as `/fetchQuestions`
- [LIME-1161](https://govukverify.atlassian.net/browse/LIME-1161)
[LIME-1161]: https://govukverify.atlassian.net/browse/LIME-1161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1161 correct fetch questions case to fetchquestions (from fetchQuestions)

---

.github/pull_request_template.md
.github/workflows/deploy-branch.yml
.github/workflows/post-merge-deploy-to-build.yml
.github/workflows/post-merge-deploy-to-dev.yml
deploy.sh
infrastructure/public-api.yaml
infrastructure/template.yaml
integration-tests/tests/aws/fetch-questions/fetch-questions-happy.test.ts
lambdas/fetch-questions/src/services/questions-retrieval-service.ts

FetchQuestionsLambda
- Placed Lambda in the protected VPC subnet
- Minor fix to a log line
ApiGateways
Public/Private
- Enabled Usage plans in pipeline based deployments
- Set DataTraceEnabled=false in production env
- Aligned Rate Limits to the current values in passport/dl/fraud
- Named the Gateways
Public API
- Enabled use of API Keys and require it only in request in pipeline based deployments
Template
- Disabled code signing if arn is not provided
- Added LoggingKmsKey
- Added Named log groups
- Set retention to 30 days in all log groups
- Added place holder csls subscription filters	+ LogSendingEnabled conditional
Actions
- Align preview stack deploy with expected non-pipeline values
- Update deploy to dev, and package for build
Changes are to align with PassportCRI template which …

LIME-1163 Align template with passport-cri

---

lambdas/fetch-questions/src/services/questions-retrieval-service.ts
lambdas/fetch-questions/tests/services/questions-retrieval-service.test.ts
lambdas/submit-answer/src/services/submit-answer-service.ts
package-lock.json
step-functions/fetch-questions.asl.json
step-functions/post-answer.asl.json

Changed to fetching parameters individually to correct parameters in fetch-questions/post-answer sometimes being re-ordered.
When prefix was enabled the parameter order can be reversed (url/useragent). 
Using hardcoded array indexes are not safe in this scenario.
- [LIME-1128](https://govukverify.atlassian.net/browse/LIME-1128)
[LIME-1128]: https://govukverify.atlassian.net/browse/LIME-1128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1128 Correct parameters in fetch-questions/post-answer sometimes being re-ordered

---

lambdas/evidence-check-details/src/check-details-handler.ts
lambdas/execute-state-machine/src/execute-state-machine-handler.ts
lambdas/fetch-questions/src/fetch-questions-handler.ts
lambdas/fetch-questions/src/services/filter-questions-service.ts
lambdas/fetch-questions/src/services/questions-retrieval-service.ts
lambdas/fetch-questions/tests/fetch-questions-handler.test.ts
lambdas/fetch-questions/tests/jest.custom.ts
lambdas/fetch-questions/tests/services/filter-questions-service.test.ts
lambdas/fetch-questions/tests/services/questions-retrieval-service.test.ts
lambdas/fetch-questions/tsconfig.json
lambdas/issue-credential/src/issue-credential-handler.ts
lambdas/issue-credential/src/time-handler.ts
lambdas/issue-credential/tests/issue-credential-handler.test.ts
lambdas/jwt-signer/src/jwt-signer-handler.ts
lambdas/submit-answer/src/create-auth-code-handler.ts
lambdas/submit-answer/src/services/submit-answer-service.ts
lambdas/submit-answer/src/submit-answer-handler.ts
lambdas/submit-answer/tests/services/submit-answer-service.disabled.ts
lambdas/time/src/current-time-handler.ts
lib/src/Service/metrics-probe.ts
lib/src/Service/stop-watch.ts
package-lock.json
package.json

- Updates CRI to powertools 2.5.0
- Update MetricsProbe to use 2.5.0
- Corrects logger name in several files
- Add cold start tracking to SubmitAnswerHandler/IssueCredentialHandler
- Add stopwatch class for latency calculation
- Add indepth pre and post filter category tracking in filter questions
- Update filter questions tests to assert metrics are called correctly
- Add custom matcher to support dynamic outcomes in filter questions tests
- Add latency tracking for happy/error paths in submit question
- Adds lambda completion tracking to IssueCredentialHandler
To track key metrics in the current hmrc kbv journey
- [LIME-1085](https://govukverify.atlassian.net/browse/LIME-1085)
[LIME-1085]: https://govukverify.atlassian.net/browse/LIME-1085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …

LIME-1085 Ensure we are tracking key metrics

---

.github/jest.config.ci.ts
.secrets.baseline
infrastructure/template.yaml
jest.config.base.ts
lambdas/answer-validation/jest.config.ts
lambdas/answer-validation/package.json
lambdas/answer-validation/src/answer-validation-handler.ts
lambdas/answer-validation/tests/answer-validation-handler.test.ts
lambdas/answer-validation/tsconfig.json
package-lock.json
package.json
step-functions/post-answer.asl.json

New lambda to handle validation of the answers after they've been received from the front end. This is part of the post-answers state machine and step function.
To add another level of validation to ensure the values are correct before being sent to HMRC IVQ api.
- [LIME-1096](https://govukverify.atlassian.net/browse/LIME-1096)
[LIME-1096]: https://govukverify.atlassian.net/browse/LIME-1096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1096 Validating answers

---

.github/jest.config.ci.ts
feature-tests/tests/resources/step-definitions/post-answer-happy-path.step.ts
feature-tests/utils/create-session.ts
infrastructure/template.yaml
jest.config.base.ts
lambdas/answer-validation/src/answer-validation-handler.ts
lambdas/submit-answer/src/services/results-service.ts
lambdas/submit-answer/src/submit-answer-handler.ts
lambdas/submit-answer/src/types/answer-result-types.ts
step-functions/post-answer.asl.json

- Add Session Check to PostAnswers statemachien
- Use SessioItem's TTL value in AnswersTable DB save
- Correct AnswersTable DB save TTL (S->N)
- Add basic validation to SubmitAnswerHandler
- use incomming sessionItem's TTL in answers save
- Correct fieldname used for TTL to expiryDate (ttl in several places)
To ensure dynamodb items expire as expected.
- [LIME-1111](https://govukverify.atlassian.net/browse/LIME-1111)
[LIME-1111]: https://govukverify.atlassian.net/browse/LIME-1111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1111 Confirm database set up (Correct Item Expiries)

---

lambdas/fetch-questions/src/services/questions-retrieval-service.ts
lambdas/fetch-questions/src/services/save-questions-service.ts
lambdas/fetch-questions/src/types/questions-result-types.ts
lambdas/fetch-questions/tests/services/questions-retrieval-service.test.ts
lambdas/fetch-questions/tests/services/save-questions-service.test.ts
step-functions/get-question.asl.json

Changed taxYearCurrent to CurrentTaxYear and taxYearPrevious to previousTaxYear
Changed state machine getQuestion to account for above
To align with third-party-stub
- [LIME-1204](https://govukverify.atlassian.net/browse/LIME-1204)
[LIME-1204]: https://govukverify.atlassian.net/browse/LIME-1204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1204 tax year variable name fix

---

feature-tests/README.md
feature-tests/apiEndpoints/endpoints.ts
feature-tests/jest.config.ts
feature-tests/package-lock.json
feature-tests/package.json
feature-tests/tests/resources/features/createSession/createSessionRequest-sessionId-HappyPath.feature
feature-tests/tests/resources/features/hmrcGet/hmrcQuestion-HappyPath.feature
feature-tests/tests/resources/features/hmrcGet/hmrcQuestion-UnhappyPath.feature
feature-tests/tests/resources/features/hmrcPost/hmrcAnswer-HappyPath.feature
feature-tests/tests/resources/features/hmrcPost/hmrcAnswer-UnhappyPath.feature
feature-tests/tests/resources/features/hmrcPost/hmrcFetchQuestions-HappyPath.feature
feature-tests/tests/resources/features/hmrcPost/hmrcFetchQuestions-UnhappyPath.feature
feature-tests/tests/resources/step-definitions/create-session-request-happy-path.step.ts
feature-tests/tests/resources/step-definitions/get-question-happy-path.step.ts
feature-tests/tests/resources/step-definitions/get-question-unhappy-path.step.ts
feature-tests/tests/resources/step-definitions/post-answer-happy-path.step.ts
feature-tests/tests/resources/step-definitions/post-answer-unhappy-path.step.ts
feature-tests/tests/resources/step-definitions/post-fetchquestions-happy-path.step.ts
feature-tests/tests/resources/step-definitions/post-fetchquestions-unhappy-path.step.ts
feature-tests/utils/answer_body.ts
feature-tests/utils/constants.ts
feature-tests/utils/create-session.ts
feature-tests/utils/jwt-utils.ts
feature-tests/utils/logger.ts
feature-tests/utils/utility.ts
infrastructure/public-api.yaml
lambdas/fetch-questions/src/services/filter-questions-service.ts

Update the feature-tests repo method to decrypt the returned VC data, move to a separate method
Add additional UnhappyPath feature tests
Update Answer Happy Path tests to validate the details of the returned VC (PersonalNumber and VerificationScore)
Method for Decrypting JWT Payload added
Logger.ts file added
constants.ts file added
UnHappy Path featurefile and steps for fetchQuestions and Questions and Answers Added/Updated
Provide stability to the Decrypt Method and allow for validation against returned VC
increase coverage of UnHappy Path Tests
- [LIME-1227](https://govukverify.atlassian.net/browse/LIME-1227)
Test Passing locally: 
4 tests failing, to be investigated with Devs (Invalid Header Values) 
[LIME-1227]: https://govukverify.atlassian.net/browse/LIME-1227?atlOrigin=eyJpIjoiNWRk …

LIME-1227: Added separate method for decrypting the VC

---

feature-tests/run-tests.sh

Updated run-tests.sh file with new params
To allow the test image running against the Build and Staging Pipelines to execute in AWS CodePipeline 
- [LIME-1215](https://govukverify.atlassian.net/browse/LIME-1215)
[LIME-1215]: https://govukverify.atlassian.net/browse/LIME-1215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1215]: https://govukverify.atlassian.net/browse/LIME-1215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1215: Updated run-tests.sh with new params for Pipeline Execution

---

feature-tests/Dockerfile
feature-tests/tests/resources/step-definitions/ui/question-page.step.ts

Update Docker File to include Chrome Install
To enable Pipeline Tests running in Chrome-headless
- [LIME-1215](https://govukverify.atlassian.net/browse/LIME-1215)
[LIME-1215]: https://govukverify.atlassian.net/browse/LIME-1215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1215]: https://govukverify.atlassian.net/browse/LIME-1215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1215: Update DockerFile to install Chrome

---

infrastructure/private-api.yaml
step-functions/get-question.asl.json

Correctly handle the absence of previous tax year in GetQuestions Statemachine.
Update VTL to output valid json when previous tax year is not found.
GetQuestions Statemachine was unable to handle the absence of previousTax year.
When Statemachine was corrected the JSON outputted by the VTL was invalid.
- [LIME-1197](https://govukverify.atlassian.net/browse/LIME-1197)
[LIME-1197]: https://govukverify.atlassian.net/browse/LIME-1197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1197 Correct get question statemachine info field handling and correct VTL json output to account for dynamic behaviour of info field

---

feature-tests/jest.config.ts
feature-tests/package-lock.json
feature-tests/package.json
feature-tests/tests/resources/features/createSession/createSessionRequest-sessionId-HappyPath.feature
feature-tests/tests/resources/features/hmrcGet/hmrcQuestion-HappyPath.feature
feature-tests/tests/resources/features/hmrcGet/hmrcQuestion-UnhappyPath.feature
feature-tests/tests/resources/features/hmrcPost/hmrcAnswer-HappyPath.feature
feature-tests/tests/resources/features/hmrcPost/hmrcAnswer-UnhappyPath.feature
feature-tests/tests/resources/features/hmrcPost/hmrcFetchQuestions-HappyPath.feature
feature-tests/tests/resources/features/hmrcPost/hmrcFetchQuestions-UnhappyPath.feature
feature-tests/tests/resources/features/ui/hmrcGet/hmrcQuestion-HappyPath.feature
feature-tests/tests/resources/features/ui/hmrcPost/hmrcAnswer-HappyPath.feature
feature-tests/tests/resources/step-definitions/create-session-request-happy-path.step.ts
feature-tests/tests/resources/step-definitions/get-question-happy-path.step.ts
feature-tests/tests/resources/step-definitions/get-question-unhappy-path.step.ts
feature-tests/tests/resources/step-definitions/post-answer-happy-path.step.ts
feature-tests/tests/resources/step-definitions/post-answer-unhappy-path.step.ts
feature-tests/tests/resources/step-definitions/post-fetchquestions-happy-path.step.ts
feature-tests/tests/resources/step-definitions/post-fetchquestions-unhappy-path.step.ts
feature-tests/tests/resources/step-definitions/ui/context-page.step.ts
feature-tests/tests/resources/step-definitions/ui/question-page.step.ts
feature-tests/utils/answer_body.ts
feature-tests/utils/create-session.ts

Including coverage of verification score 2 and 0
update step to use verificationScore from the example in the cucumber file added new tests for when 2 questions from 2 questionKeys is supplied Added API tests for malformed response from question endpoint Added cucumber Test Reporting for feature-tests
Added new Happy Path tests for FE feature-tests
Added cucumber-html-reporter to generate cucumber reports
- [LIME-1259](https://govukverify.atlassian.net/browse/LIME-1259)
[LIME-1259]: https://govukverify.atlassian.net/browse/LIME-1259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1259]: https://govukverify.atlassian.net/browse/LIME-1259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1259: Added new Happy Path tests for FE E2E tests

---

.github/workflows/run-unit-tests.yml

the infra tests will now be executed inside of the test:coverage package.json command, which will be picked up and run on the run-unit-tests.yml github workflow
Updated the main run-unit-tests.yml file to run the infra tests as part of its own action
To enable the infra tests to be run as part of the run-unit-tests.yml github workflow
- [LIME-1129](https://govukverify.atlassian.net/browse/LIME-1129)
All Tests passed in checks for infra alarm tests:
[LIME-1129]: https://govukverify.atlassian.net/browse/LIME-1129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1129: Updated package.json to run infra tests

---

lambdas/ssm-parameters/src/ssm-parameters-handler.ts
lambdas/ssm-parameters/src/types/strategy.ts
lambdas/ssm-parameters/tests/ssm-parameters-handler.test.ts

- Add Auto Parsing of JSON to SSM parameter fetches if the value contains all the strategy route strings
- - Return the value from the Parsed JSON for the current strategy
- - Error out if the above fails
- Fallback to standard string value returns if the value has none of the route strings.
- Add Unit test coverage for the above
- Correct Strategy Enum string values to all caps to avoid ambiguity of the exact string value required
To Implement test data strategy
- [LIME-1099](https://govukverify.atlassian.net/browse/LIME-1099)
[LIME-1099]: https://govukverify.atlassian.net/browse/LIME-1099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1099 - Implement test data strategy

---

lambdas/submit-answer/src/submit-answer-handler.ts
lambdas/submit-answer/tests/submit-answer-handler.test.ts

Fix incorrect token value used for answers api request
Answers API request failed due to the incorrect value
- [LIME-1285](https://govukverify.atlassian.net/browse/LIME-1285)
[LIME-1285]: https://govukverify.atlassian.net/browse/LIME-1285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1285 Fix incorrect token value used for answers api request

---

lambdas/issue-credential/src/issue-credential-handler.ts

Updated nbf field to be in seconds instead of miliseconds

LIME-1262 - Updating Nbf field in VC to be in seconds

---

.secrets.baseline
infrastructure/template.yaml

Ensure log groups are all set to 30 days retention
To ensure log groups do not have extended retention lengths
- [LIME-1169](https://govukverify.atlassian.net/browse/LIME-1169)
[LIME-1169]: https://govukverify.atlassian.net/browse/LIME-1169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1169 Set log group retention in days to 30 for all log groups

---

.github/workflows/deploy-branch.yml

prefix is 20 chars, max Lambda function name length is 64, the lambdas in this template use `prefix-stackname-resource-name` so limiting `prefix-stackname` to 34 char leaving 30 for resource names
My last PR failed checked with this error:
```
CREATE_FAILED            AWS::Lambda::Function    AnswerValidationFuncti   Resource handler       
on                       returned message: "1   
validation error       
detected: Value        
'preview-kbv-hmrc-api- 
psredev-1911-dev-      
platform-support-      
request-adam-          
higginson-answer-      
validation' at         
'functionName' failed  
to satisfy constraint: 
Member must have       
length less than or    
equal to 64 (Service:  
Lambda, Status Code:   
400, Request ID: e3a52 
f93-3b98-4115-adcf-    
072de2e5218c)" …
```

The stack name needs to be limited at 34

---

infrastructure/template.yaml

Disable alarm actions for HMRC KBV API
Cloudwatch alarm actions disabled in Cloud formation template.yaml
When alarm 'actions enabled' is set to false, Pagerduty should not receive notifications
- [LIME-1469](https://govukverify.atlassian.net/browse/LIME-1469)
[LIME-1469]: https://govukverify.atlassian.net/browse/LIME-1469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1469 disabled alarm actions

---

infrastructure/template.yaml

API request throttle limits and lambda logging retention days reduced. 
To reduce maintenance costs for decommissioning of HMRC KBV CRI.
- [LIME-1466](https://govukverify.atlassian.net/browse/LIME-1466)
- Successful user journey completed locally 
[LIME-1466]: https://govukverify.atlassian.net/browse/LIME-1466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1466 updates Lambda config for decom

---

feature-tests/package.json
lambdas/jwt-signer/package.json
package-lock.json
package.json

Apply necessary security patches and updates to maintain a secure codebase
Updated the  @aws-sdk/credential-providers dependency to address a vulnerable subdependency
patched version applied: 
- [LIME-1467](https://govukverify.atlassian.net/browse/LIME-1467)
[LIME-1467]: https://govukverify.atlassian.net/browse/LIME-1467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1467 added security fixes

---

.github/dependabot.yml
.gitignore

- Added github actions to the dependabot config
- Add .DS_Store to gitignore
- Dependabot will raise automatic PRs to increase the versions of repos used in the github actions workflows
- Keeps code up to data and fixes errors
- [IPS-527](https://govukverify.atlassian.net/browse/IPS-527)
[IPS-527]: https://govukverify.atlassian.net/browse/IPS-527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-527: Add dependabot config

---

feature-tests/tests/resources/features/createSession/createSessionRequest-sessionId-HappyPath.feature
feature-tests/tests/resources/features/hmrcGet/hmrcQuestion-HappyPath.feature
feature-tests/tests/resources/features/hmrcGet/hmrcQuestion-UnhappyPath.feature
feature-tests/tests/resources/features/hmrcPost/hmrcAnswer-HappyPath.feature
feature-tests/tests/resources/features/hmrcPost/hmrcAnswer-UnhappyPath.feature
feature-tests/tests/resources/features/hmrcPost/hmrcFetchQuestions-HappyPath.feature
feature-tests/tests/resources/features/hmrcPost/hmrcFetchQuestions-UnhappyPath.feature
feature-tests/tests/resources/features/ui/hmrcGet/hmrcQuestion-HappyPath.feature
feature-tests/tests/resources/features/ui/hmrcPost/hmrcAnswer-HappyPath.feature
feature-tests/tests/resources/page/stub-page.ts
feature-tests/tests/resources/step-definitions/ui/context-page.step.ts
feature-tests/tests/resources/step-definitions/ui/question-page.step.ts
package.json

Disabled Test Tags for all tests
All tests for UI and API have had test tags commented out (this includes all pre merge and post merge tests)  
Package.json script for Infrastructure template tests removed (disables the infra template tests) 
**Workflows:**
run-unit-tests.yml updated to remove Infra Tests from being run as part of unit tests  
To ensure that tests dont execute unexpectedly during HMRC Close down tasks
- [LIME-1517](https://govukverify.atlassian.net/browse/LIME-1517)
[LIME-1517]: https://govukverify.atlassian.net/browse/LIME-1517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1517: Disable Tests on BE Repo (UI + API) for HMRC KBV Closing Down

---

.secrets.baseline
infrastructure/template.yaml

Rate limit higher environments but keep dev and pre-merge operational
To reduce running costs of inactive environments.
- [LIME-1466](https://govukverify.atlassian.net/browse/LIME-1466)
[LIME-1466]: https://govukverify.atlassian.net/browse/LIME-1466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1466 - Rate limit higher environments but keep dev and pre-merge operational
