infrastructure/samconfig.toml
infrastructure/template.yaml
step-functions/get-question.asl.json
step-functions/post-answer.asl.json

Added cfn for state machines so that they are deployable

Add state machine infrastructure

---

infrastructure/template.yaml
step-functions/post-answer.asl.json

Updates to post-answer to be deployed dynamically.
Moving away from Spike
- [OJ-1801](https://govukverify.atlassian.net/browse/OJ-1801)
[OJ-1801]: https://govukverify.atlassian.net/browse/OJ-1801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1801-Permissions and refactoring

---

infrastructure/template.yaml
step-functions/get-question.asl.json

Integrate state machine infrastructure together

---

infrastructure/template.yaml
step-functions/get-question.asl.json

Get Question was changed back to sync 2
Added necessary permission to get sync2 working
Get Question was not working correctly

BAU: added permission for get question state sync2

---

.github/workflows/post-merge-deploy-to-build.yml
.github/workflows/post-merge-deploy-to-dev.yml

- Added workflow file to deploy to dev and build
- CI/CD

chore: added HMRC workflows to deploy to dev and build.

---

infrastructure/private-api.yaml
infrastructure/public-api.yaml
infrastructure/samconfig.toml
infrastructure/template.yaml

Added the endpoints in front of the common lambdas now that they're deployed to KBV HMRC
Added a public API for the /token endpoint
- [OJ-1840](https://govukverify.atlassian.net/browse/OJ-1840)
[OJ-1840]: https://govukverify.atlassian.net/browse/OJ-1840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1840 add common lambdas endpoints and public API

---

infrastructure/template.yaml
step-functions/post-ivq-answers.asl.json

`template.yaml` to add the write permissions to the questions table
`post-ivq-answers.asl.json` added the state to store the response from HMRC
To generate a VC, we will need to know which questions the user got correct and incorrect.
- [OJ-1841](https://govukverify.atlassian.net/browse/OJ-1841)
[OJ-1841]: https://govukverify.atlassian.net/browse/OJ-1841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BAU: Added Store Answer to post-ivq-answers state machine

---

infrastructure/template.yaml
lambdas/issue-credential/.eslintignore
lambdas/issue-credential/.eslintrc.js
lambdas/issue-credential/jest.config.ts
lambdas/issue-credential/package-lock.json
lambdas/issue-credential/package.json
lambdas/issue-credential/src/time-event.ts
lambdas/issue-credential/src/time-handler.ts
lambdas/issue-credential/tests/time-handler.test.ts
lambdas/issue-credential/tsconfig.json
step-functions/issue-credential.asl.json

Added files to support the issue-credential state machine.
To generate a VC
- [OJ-1841](https://govukverify.atlassian.net/browse/OJ-1841)
[OJ-1841]: https://govukverify.atlassian.net/browse/OJ-1841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1841: HMRC KBV Issue Credential State Machine

---

infrastructure/samconfig.toml
infrastructure/template.yaml
step-functions/issue-credential.asl.json

Allow for pointing state machines at own common stack
- [OJ-1891](https://govukverify.atlassian.net/browse/OJ-1891)
[OJ-1891]: https://govukverify.atlassian.net/browse/OJ-1891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1891 common stack name substitution

---

step-functions/post-answer.asl.json

Changed the check condition for answer to be `value` instead of `key`.
`answer` wasn't being checked properly and instead the condition was checking for the question key. 

[BAU]: Fixed check answer present condition

---

infrastructure/template.yaml
integration-tests/tests/aws/kbv-check-happy.test.ts
integration-tests/tests/aws/kbv-check-unhappy.test.ts
integration-tests/tests/aws/resources/cloudformation-helper.ts
integration-tests/tests/aws/resources/dynamodb-helper.ts
integration-tests/tests/aws/resources/stepfunction-helper.ts

Oj 1884 get questions aws tests

---

integration-tests/tests/aws/get-ivq-questions/get-ivq-questions-unhappy.test.ts
integration-tests/tests/aws/resources/ssm-param-helper.ts

Added unhappy test
- [OJ-1886](https://govukverify.atlassian.net/browse/OJ-1886)
[OJ-1886]: https://govukverify.atlassian.net/browse/OJ-1886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1886 added unhappy test

---

infrastructure/template.yaml
integration-tests/tests/aws/post-questions/post-questions-happy.test.ts
integration-tests/tests/aws/post-questions/post-questions-unhappy.test.ts

Added aws test for post-answer state machine
- [OJ-1890](https://govukverify.atlassian.net/browse/OJ-1890)
[OJ-1890]: https://govukverify.atlassian.net/browse/OJ-1890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1890-post-answers-aws-tests

---

step-functions/get-ivq-questions.asl.json

Replace map with looping logic, to store a collection of questions
Replaced Map State with looping logic
Map state breaks step function local testing

OJ-1927: Replace map with loop logic

---

infrastructure/template.yaml
lambdas/credential-subject/.eslintignore
lambdas/credential-subject/.eslintrc.js
lambdas/credential-subject/jest.config.ts
lambdas/credential-subject/package-lock.json
lambdas/credential-subject/package.json
lambdas/credential-subject/src/credential-subject-builder.ts
lambdas/credential-subject/src/credential-subject-handler.ts
lambdas/credential-subject/src/user-info-event.ts
lambdas/credential-subject/tests/credential-subject-builder.test.ts
lambdas/credential-subject/tests/credential-subject-handler.test.ts
step-functions/issue-credential.asl.json

Replace credential-subject maps with lambda implementations
Replace Map state Create Credential Subject with lambda
Map states don't work with step-function local
- [OJ-1928](https://govukverify.atlassian.net/browse/OJ-1928)
[OJ-1928]: https://govukverify.atlassian.net/browse/OJ-1928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1928: replace map state in hmrc kbv part 2

---

.pre-commit-config.yaml

Remove package-lock from large file pre-commit checks

BAU: Remove package-lock from large check

---

infrastructure/template.yaml
integration-tests/tests/aws/post-ivq-answers/post-ivq-answers-happy.test.ts
integration-tests/tests/aws/resources/dynamodb-helper.ts

aws test have been created
- [OJ-1888](https://govukverify.atlassian.net/browse/OJ-1888)
[OJ-1888]: https://govukverify.atlassian.net/browse/OJ-1888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1888 aws tests

---

step-functions/get-question.asl.json

State machine will 400/500 in error scenarios. 
State machine will 200 if OK or 204 when there are no more questions (as in Experian KBV)
- [OJ-1955](https://govukverify.atlassian.net/browse/OJ-1955)
[OJ-1955]: https://govukverify.atlassian.net/browse/OJ-1955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1955: Added error states to state machine

---

integration-tests/tests/mocked/get-question/MockConfigFile.json
integration-tests/tests/mocked/get-question/get-question-happy.test.ts
integration-tests/tests/mocked/get-question/get-question-unhappy.test.ts
integration-tests/tests/mocked/get-question/makefile
integration-tests/tests/mocked/get-question/sfn-container-helper.ts

The mocked tests have been updated to handle the state machine changes. 
The sfn helper can now work with failed executions.
Mocked tests were failing.

BAU: Fix mocked tests for get-question state machine

---

integration-tests/tests/aws/get-ivq-questions/get-ivq-questions-happy.test.ts
integration-tests/tests/aws/get-ivq-questions/get-ivq-questions-unhappy.test.ts

The tests were failing after changes were made in state machine hence these PR to fix those tests
- [OJ-1965](https://govukverify.atlassian.net/browse/OJ-1965)
[OJ-1965]: https://govukverify.atlassian.net/browse/OJ-1965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1965 refactor aws tests

---

infrastructure/private-api.yaml
step-functions/post-answer.asl.json

Removed input check from state machine as this is already handled by the APIGW. 
Added fail states for 500 errors and pass states for 400 errors. 
Updated private-api to respond with correct status code. 
- [OJ-1954](https://govukverify.atlassian.net/browse/OJ-1954)
[OJ-1954]: https://govukverify.atlassian.net/browse/OJ-1954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1954: PostAnswer state machine error handling

---

integration-tests/tests/aws/post-answers/post-answers-happy.test.ts
integration-tests/tests/aws/post-answers/post-answers-unhappy.test.ts

file renaming
- [OJ-1967](https://govukverify.atlassian.net/browse/OJ-1967)
[OJ-1967]: https://govukverify.atlassian.net/browse/OJ-1967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1967 rename post answer files

---

integration-tests/tests/aws/get-question/get-question-happy.test.ts
integration-tests/tests/aws/get-question/get-question-unhappy.test.ts
integration-tests/tests/aws/post-answers/post-answers-unhappy.test.ts
integration-tests/tests/aws/post-ivq-answers/post-ivq-answers-happy.test.ts

This PR is to fix the aws failing tests
- [OJ-1974](https://govukverify.atlassian.net/browse/OJ-1974)
[OJ-1974]: https://govukverify.atlassian.net/browse/OJ-1974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1974 fixed aws failing tests

---

.github/workflows/post-merge-deploy-to-build.yml

The github workflows
So we can manually trigger actions, there have been times were we need to run GHAs manually for testing and debugging but we can't at the moment without making a new PR

OJ-1990: Added workflow_dispatch to GHA

---

infrastructure/template.yaml
lambdas/time/.eslintignore
lambdas/time/.eslintrc.js
lambdas/time/jest.config.ts
lambdas/time/package-lock.json
lambdas/time/package.json
lambdas/time/src/current-time-handler.ts
lambdas/time/tests/current-time-handler.test.ts
lambdas/time/tsconfig.json
step-functions/check_session.asl.json

Added check-session state machine.
So we can add `session-id` verification where appropriate to the HMRC KBV state machines. This PR just adds the state machine in but no changes to the other state machines done.

BAU: Added session-check state machine

---

.github/workflows/post-merge-deploy-to-build.yml

post merge push to build workflow secret names
The secret names were incorrect

correct workflow secret names

---

infrastructure/template.yaml
step-functions/post-answer.asl.json

- updating state machine permissions
- lambda VPC policy

LIME-1090 - updating state machine permissions and lambda VPC policy

---

lambdas/submit-answer/src/services/submit-answer-service.ts

LIME-1090 - updating answer result json mapping

---

lambdas/submit-answer/src/services/submit-answer-service.ts
lambdas/submit-answer/src/submit-answer-handler.ts

Performed check to ensure if there was only one question is was treated correctly
To allow single question responses to pass

LIME-1090: Fix to allow single question responses

---

.github/workflows/post-merge-deploy-to-build.yml
.github/workflows/post-merge-deploy-to-dev.yml

IPS-812 - Updated upload actions version to 3.9
- [IPS-812](https://govukverify.atlassian.net/browse/IPS-812)
[IPS-812]: https://govukverify.atlassian.net/browse/IPS-812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-812 - Updated upload actions version to 3.9

---

.secrets.baseline
infrastructure/public-api.yaml
infrastructure/template.yaml
lambdas/issue-credential/src/issue-credential-handler.ts
lambdas/issue-credential/tests/issue-credential-handler.test.ts
lambdas/jwt-signer/jest.config.ts
lambdas/jwt-signer/package.json
lambdas/jwt-signer/src/jwt-signer-handler.ts
lambdas/jwt-signer/src/signage-type.ts
lambdas/jwt-signer/src/signer-payload.ts
lambdas/jwt-signer/tests/jwt-signer-handler.test.ts
lambdas/jwt-signer/tests/test-data.ts
lambdas/jwt-signer/tsconfig.json
package-lock.json
package.json
step-functions/issue-credential.asl.json

Two new lambdas have been created:
1. Issue Credential Lambda - To handle a request to generate a VC: The infrastructure has been created 
2. JWT Signer Lambda - For signing the Lambda
The step functions have been updated to handle the request prior to either lambda being triggered by the request. This handles adding the header, body and signature together for the final encrypted VC. 
- [LIME-1092](https://govukverify.atlassian.net/browse/LIME-1092)
[LIME-1092]: https://govukverify.atlassian.net/browse/LIME-1092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1092 Creation of VC lambda

---

lambdas/fetch-questions/src/fetch-questions-handler.ts
lambdas/fetch-questions/src/services/filter-questions-service.ts
lambdas/fetch-questions/tests/fetch-questions-handler.test.ts
lambdas/fetch-questions/tests/services/filter-questions-service.test.ts
package-lock.json

This PR has created the filterQuestionService which has been added into the fetch-questions-handler, and tests have been updated to account for its logic in the flow between retrieving questions from HMRC, and saving to Dynamo.
The questions have been filtered to ensure the questions which will be saved match our requirements for GPG45 and will only save the required number of questions to Dynamo.
- [LIME-1081](https://govukverify.atlassian.net/browse/LIME-1081)
[LIME-1081]: https://govukverify.atlassian.net/browse/LIME-1081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1081 Filtering HMRC Question Keys

---

infrastructure/template.yaml
lambdas/issue-credential/src/issue-credential-handler.ts
lambdas/issue-credential/src/utils/check-details-builder.ts
lambdas/issue-credential/src/utils/evidence-builder.ts
lambdas/issue-credential/tests/issue-credential-handler.test.ts
lambdas/submit-answer/src/services/results-service.ts
lambdas/submit-answer/src/submit-answer-handler.ts
lambdas/submit-answer/src/types/answer-result-types.ts
lambdas/submit-answer/src/utils/check-details-count-calculator.ts
lambdas/submit-answer/tests/services/results-service.test.ts
lambdas/submit-answer/tests/utils/check-details-count-calculator.test.ts
lambdas/submit-answer/tests/utils/verification-score-calculator.test.ts
package-lock.json
package.json

- Added check/failed check details functionality to VC
- Added contra Indicator logic to VCs
- added environment variable and permissions to template to allow contra indicator parameter get
- Updated tests

LIME-1193 - failed/checkDetails and CI added to VC

---

.github/workflows/post-merge-deploy-to-build.yml
.github/workflows/run-pre-merge-integration-tests.yml
.github/workflows/smoke-tests-build.yml
.secrets.baseline
feature-tests/Dockerfile
feature-tests/apiEndpoints/endpoints.ts
feature-tests/jest.config.ts
feature-tests/package.json
feature-tests/run-tests.sh
feature-tests/tests/resources/features/createSession/createSessionRequest-sessionId-HappyPath.feature
feature-tests/tests/resources/features/hmrcGet/hmrcQuestion-HappyPath.feature
feature-tests/tests/resources/features/hmrcPost/hmrcAnswer-HappyPath.feature
feature-tests/tests/resources/features/hmrcPost/hmrcAnswer-UnhappyPath.feature
feature-tests/tests/resources/features/hmrcPost/hmrcFetchQuestions-HappyPath.feature
feature-tests/tests/resources/step-definitions/create-session-request-happy-path.step.ts
feature-tests/tests/resources/step-definitions/get-question-happy-path.step.ts
feature-tests/tests/resources/step-definitions/post-answer-happy-path.step.ts
feature-tests/tests/resources/step-definitions/post-answer-unhappy-path.step.ts
feature-tests/tests/resources/step-definitions/post-fetchquestions-happy-path.step.ts
feature-tests/tsconfig.json
feature-tests/utils/answer_body.ts
feature-tests/utils/create-session.ts
feature-tests/utils/utility.ts
infrastructure/template.yaml
integration-tests/tests/aws/fetch-questions/fetch-questions-happy.test.ts
integration-tests/tests/aws/fetch-questions/fetch-questions-unhappy.test.ts
lambdas/fetch-questions/src/fetch-questions-handler.ts
lambdas/fetch-questions/src/services/filter-questions-service.ts

Updated feature-tests framework to include workflow to test Post Merge
Updated feature-tests framework to include additional Answers Endpoint Happy Path Tests
Updated feature-tests framework to include Answers Endpoint Unhappy Path Tests
To allow for feature-tests to be executed post merge of PRs
- [LIME-1107](https://govukverify.atlassian.net/browse/LIME-1107)
Test Evidence: 
[LIME-1107]: https://govukverify.atlassian.net/browse/LIME-1107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1107]: https://govukverify.atlassian.net/browse/LIME-1107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1107 - Add Post Merge workflow checks to feature-tests

---

.github/workflows/check-pr.yml
.github/workflows/post-merge-deploy-to-build.yml
.github/workflows/run-aws-tests.yml
.github/workflows/smoke-tests-build.yml
.secrets.baseline
deploy.sh
feature-tests/tests/resources/step-definitions/post-answer-happy-path.step.ts
feature-tests/utils/answer_body.ts
feature-tests/utils/create-session.ts
integration-tests/tests/aws/fetch-questions/fetch-questions-happy.test.ts
integration-tests/tests/aws/fetch-questions/fetch-questions-unhappy.test.ts
lambdas/answer-validation/src/answer-validation-handler.ts
lambdas/fetch-questions/src/fetch-questions-handler.ts
lambdas/fetch-questions/tests/fetch-questions-handler.test.ts

- Correct json payload in SA_P_D response
- Add some debug into fetch questions (debug level)
- Add additional questionKey logging into feature tests steps.
- Add additional sessionId logging into feature tests steps.
- Removed OAuth token refresh in action - replaced with otg-token function
- Correct fetch questions integration test failing
- Correct fetch questions failing in audit service due to missing parts of sessionItem.
- Re-enable sam build cache due to build time impact
Correct intermittent failures in feature tests when SA key appears.
To enable all currently working pre-merge/post-merge checks to pass.
- [LIME-1222](https://govukverify.atlassian.net/browse/LIME-1222)
[LIME-1222]: https://govukverify.atlassian.net/browse/LIME-1222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …

LIME-1222 Correct pre-merge/post-merge check failures

---

.github/workflows/run-pre-merge-integration-tests.yml

Add missing pre-merge stack cleanup step
The environment is running out of IAM roles due to pre-merge stacks not getting deleted.
- [LIME-1128](https://govukverify.atlassian.net/browse/LIME-1128)
[LIME-1128]: https://govukverify.atlassian.net/browse/LIME-1128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1128 Add missing pre-merge stack cleanup step

---

.github/workflows/smoke-tests-build.yml
feature-tests/README.md
feature-tests/apiEndpoints/endpoints.ts
feature-tests/jest.config.ts
feature-tests/package-lock.json
feature-tests/package.json
feature-tests/tests/resources/features/hmrcPost/hmrcAnswer-HappyPath.feature
feature-tests/tests/resources/features/ui/createSession/createSessionRequest-sessionId-HappyPath.feature
feature-tests/tests/resources/features/ui/hmrcGet/hmrcQuestion-HappyPath.feature
feature-tests/tests/resources/features/ui/hmrcPost/hmrcAnswer-HappyPath.feature
feature-tests/tests/resources/page/abstract-page-object.ts
feature-tests/tests/resources/page/context-page.ts
feature-tests/tests/resources/page/question-page.ts
feature-tests/tests/resources/page/stub-page.ts
feature-tests/tests/resources/step-definitions/ui/context-page.step.ts
feature-tests/tests/resources/step-definitions/ui/question-page.step.ts
feature-tests/utils/create-session.ts
feature-tests/utils/url-key-map.ts

NEw FE feature-tests added to exisiting framework to run as post-merge tests in higher environments
To enable testing through github workflows in build. And through CodePipeline in AWS in Build/Staging
- [LIME-1231](https://govukverify.atlassian.net/browse/LIME-1231)
- [LIME-1231](https://govukverify.atlassian.net/browse/LIME-1231)
Testing Evidence: 
All Pre-merge API feature-tests passing
All Post-merge FE feature-tests passing
README.md file updated with new commands to run FE feature-tests
New endpoint param added for FRONTEND
[LIME-1231]: https://govukverify.atlassian.net/browse/LIME-1231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1231]: https://govukverify.atlassian.net/browse/LIME-1231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …

LIME-1231: FE festure-tests for HMRC KBV CRI

---

CODEOWNERS
feature-tests/tests/resources/step-definitions/ui/question-page.step.ts

Remove Orange as code owners

---

feature-tests/run-tests.sh
feature-tests/tests/resources/step-definitions/ui/question-page.step.ts

…ockerfile
Updated Run command on run-tests.sh to use CI command
To enable to FE tests to execute with chromeOptions on the FE via the AWS CodePipeline
- [LIME-1215](https://govukverify.atlassian.net/browse/LIME-1215)
[LIME-1215]: https://govukverify.atlassian.net/browse/LIME-1215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1215]: https://govukverify.atlassian.net/browse/LIME-1215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1215: Updated run command to use CI command to run FE tests

---

feature-tests/run-tests.sh

Updated run-tests.sh Report Directory
TO fix pipeline report not displaying test results
- [LIME-1279](https://govukverify.atlassian.net/browse/LIME-1279)
[LIME-1279]: https://govukverify.atlassian.net/browse/LIME-1279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1279]: https://govukverify.atlassian.net/browse/LIME-1279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1279: Updated run-tests.sh Report Directory

---

feature-tests/jest.config.ts
infrastructure/private-api.yaml
infrastructure/public-api.yaml
infrastructure/template.yaml
integration-tests/tests/aws/fetch-questions/fetch-questions-unhappy.test.ts
lambdas/fetch-questions/src/fetch-questions-handler.ts
lambdas/fetch-questions/tests/fetch-questions-handler.test.ts
lambdas/issue-credential/src/issue-credential-handler.ts
lambdas/issue-credential/src/types/issue-credential-types.ts
lambdas/issue-credential/tests/issue-credential-handler.test.ts
lambdas/ssm-parameters/jest.config.ts
lambdas/ssm-parameters/package.json
lambdas/ssm-parameters/src/ssm-parameters-handler.ts
lambdas/ssm-parameters/src/types/strategy.ts
lambdas/ssm-parameters/tests/ssm-parameters-handler.test.ts
lambdas/ssm-parameters/tests/types/strategy.test.ts
lambdas/ssm-parameters/tsconfig.json
lambdas/submit-answer/src/services/submit-answer-service.ts
lambdas/submit-answer/tests/services/submit-answer-service.test.ts
lib/src/Logging/log-helper.ts
lib/tests/Logging/log-helper.test.ts
package-lock.json
step-functions/fetch-questions.asl.json
step-functions/issue-credential.asl.json
step-functions/post-answer.asl.json

- Disabled integration tests that tested errors for invalid QuestionURL/OTG Url as the correct values will be cached in previous journeys and cannot be overriden until the cache expires in the lambda.
- Add SSMParameterRequestFailureAlarm triggering when SSMParametersFunction fails for any reason.
- Add SSMParametersFunction to FetchQuestionsStateMachine, PostAnswerStateMachine, IssueCredentialStateMachine
- - Add GetParameters permissions to SSMParametersFunction
- - Accounts for Prefixes Stackname, ParameterPrefix and CommonStackName
- - Add StrategyUtil for test data strategy (note this PR does not implement test data strategy)
- - Add Unit tests for SSMParametersFunction + StrategyUtil
- FetchQuestionsStateMachine / PostAnswerStateMachine
- - Align DefinitionSubstitutions arrangement. …

LIME-1247 - Add SSM Parameter Cache Lambda

---

feature-tests/run-tests.sh

To attempt to resolve reporting issue on codeBuild reports
Commented out code in run-tests.sh script which copys the report directory
to check that the report folder dir is getting set correctly
- [LIME-1221](https://govukverify.atlassian.net/browse/LIME-1221)
[LIME-1221]: https://govukverify.atlassian.net/browse/LIME-1221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1221]: https://govukverify.atlassian.net/browse/LIME-1221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1221: Updated run-tests.sh to change report config

---

lambdas/issue-credential/src/issue-credential-handler.ts
lambdas/issue-credential/tests/issue-credential-handler.test.ts

Added sub field from sessionItem to VCs to match expected format from core

LIME-1262 - Adding Sub field from sessionItem to VCs]

---

.github/workflows/post-merge-deploy-to-build.yml
.github/workflows/post-merge-deploy-to-dev.yml
.pre-commit-config.yaml

- Add linting step
- Run `pre-commit autoupdate`
- Code quality control
- [IPS-1132](https://govukverify.atlassian.net/browse/IPS-1132)
[IPS-1132]: https://govukverify.atlassian.net/browse/IPS-1132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-1132: Add linting
